// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CalendarController from "./component/calendar_controller";
application.register("calendar", CalendarController);

import DialogController from "./component/dialog_controller";
application.register("dialog", DialogController);

import FlatpickrController from "./component/flatpickr_controller";
application.register("flatpickr", FlatpickrController);

import GameSelectionController from "./form/game_selection_controller";
application.register("game-selection", GameSelectionController);

import MutuallyExclusiveSelectController from "./form/mutually_exclusive_select_controller";
application.register(
  "mutually-exclusive-select",
  MutuallyExclusiveSelectController,
);

import ProposalSelectionController from "./form/proposal_selection_controller";
application.register("proposal-selection", ProposalSelectionController);

import ReloadOnRestoreController from "./util/reload_on_restore_controller";
application.register("reload-on-restore", ReloadOnRestoreController);

import TimezoneController from "./util/timezone_controller";
application.register("timezone", TimezoneController);

import RailsNestedForm from "@stimulus-components/rails-nested-form";
application.register("rails-nested-form", RailsNestedForm);

import RoleRemovalController from "./form/role_removal_controller";
application.register("role-removal", RoleRemovalController);

import PagyInitializerController from "./component/pagy_initializer_controller";
application.register("pagy-initializer", PagyInitializerController);

import ScheduleSummaryWatcherController from "./form/schedule_summary_watcher_controller";
application.register(
  "schedule-summary-watcher",
  ScheduleSummaryWatcherController,
);

import ScheduleSelectionController from "./form/schedule_selection_controller";
application.register("schedule-selection", ScheduleSelectionController);

import ElementToggleController from "./component/element_toggle_controller";
application.register("element-toggle", ElementToggleController);

import SearchController from "./form/search_controller";
application.register("search", SearchController);

import AvailabilitySelectionController from "./form/availability_selection_controller";
application.register("availability-selection", AvailabilitySelectionController);

import DropdownController from "./component/dropdown_controller";
application.register("dropdown", DropdownController);

import ConfirmationController from "@stimulus-components/confirmation";
application.register("confirmation", ConfirmationController);

import FormChangeWatcherController from "./form/form_change_watcher_controller";
application.register("form-change-watcher", FormChangeWatcherController);

import FrameReloadController from "./util/frame_reload_controller";
application.register("frame-reload", FrameReloadController);

import LoadingDialogController from "./component/loading_dialog_controller";
application.register("loading-dialog", LoadingDialogController);

import NotificationController from "./component/notification_controller";
application.register("notification", NotificationController);

import ClipboardController from "./component/clipboard_controller";
application.register("clipboard", ClipboardController);

import SingleStreamController from "./util/single_stream_controller";
application.register("single-stream", SingleStreamController);

import PopoverController from "./component/stimulus_popover_controller";
application.register("stimulus-popover", PopoverController);

import AutoSubmitController from "@stimulus-components/auto-submit";
application.register("auto-submit", AutoSubmitController);

import AnchorPositionController from "./util/anchor_position_controller";
application.register("anchor-position", AnchorPositionController);

import SidebarController from "./component/sidebar_controller";
application.register("sidebar", SidebarController);

import UpcomingGameSessionUpdatesController from "./component/upcoming_game_session_updates_controller";
application.register(
  "upcoming-game-session-updates",
  UpcomingGameSessionUpdatesController,
);

import LocalTimeConversionController from "./util/local_time_conversion_controller";
application.register("local-time-conversion", LocalTimeConversionController);
